# Generated by Django 4.2.25 on 2025-11-08 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_butaca_funcion_ticket_sala_butaca_sala'),
    ]

    operations = [
        migrations.AlterField(
            model_name='butaca',
            name='fila',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='butaca',
            name='numero',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='butaca',
            name='sala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eventos.sala'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='butaca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventos.butaca'),
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('capacidad', models.PositiveIntegerField()),
                ('funcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.funcion')),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventos.sector'),
        ),
    ]
