# Generated by Django 4.2.25 on 2025-11-08 23:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventos', '0003_alter_butaca_fila_alter_butaca_numero_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='stock',
        ),
        migrations.AddField(
            model_name='evento',
            name='tipo_evento',
            field=models.CharField(choices=[('fiesta', 'Fiesta (Sectores, sin butacas)'), ('cine', 'Cine / Teatro (con butacas)')], default='fiesta', max_length=10),
        ),
        migrations.AlterField(
            model_name='evento',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='ubicacion',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='evento',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
