# Generated by Django 4.2.25 on 2025-11-08 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_remove_evento_stock_evento_tipo_evento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='evento',
            name='tipo_evento',
            field=models.CharField(choices=[('fiesta', 'Fiesta (Sectores / Entradas)'), ('cine', 'Cine / Teatro (Butacas individuales)')], default='fiesta', max_length=10),
        ),
        migrations.AlterField(
            model_name='evento',
            name='ubicacion',
            field=models.CharField(max_length=200),
        ),
    ]
