# Generated by Django 4.2.25 on 2025-11-08 23:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventos', '0005_remove_evento_usuario_alter_evento_tipo_evento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='evento',
            name='tipo_evento',
            field=models.CharField(choices=[('fiesta', 'Fiesta (Sectores / Entradas)'), ('cine', 'Cine / Teatro (Butacas)')], default='fiesta', max_length=10),
        ),
    ]
