# Generated by Django 4.2.25 on 2025-11-08 23:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventos', '0006_evento_usuario_alter_evento_tipo_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='evento',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='evento',
            name='precio',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='evento',
            name='tipo_evento',
            field=models.CharField(choices=[('cine', 'Cine / Teatro (Butacas Numeradas)'), ('fiesta', 'Fiesta / Concierto (Sectores / Mesas)')], default='fiesta', max_length=20),
        ),
        migrations.AlterField(
            model_name='evento',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='evento',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
