# Generated by Django 5.2.7 on 2025-11-09 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0007_evento_stock_alter_evento_nombre_alter_evento_precio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('publicado', 'Publicado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
    ]
