# Generated by Django 5.1.4 on 2025-11-10 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0008_evento_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
