# Generated by Django 5.2.5 on 2025-11-11 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0009_alter_evento_ubicacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='butaca',
        ),
        migrations.RemoveField(
            model_name='funcion',
            name='evento',
        ),
        migrations.RemoveField(
            model_name='sala',
            name='funcion',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='funcion',
        ),
        migrations.RemoveField(
            model_name='sector',
            name='funcion',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='sector',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='tipo_evento',
        ),
        migrations.DeleteModel(
            name='Butaca',
        ),
        migrations.DeleteModel(
            name='Sala',
        ),
        migrations.DeleteModel(
            name='Funcion',
        ),
        migrations.DeleteModel(
            name='Sector',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
