# Generated by Django 5.2.7 on 2025-11-11 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0010_remove_ticket_butaca_remove_funcion_evento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(blank=True, max_length=50)),
                ('filas', models.PositiveIntegerField()),
                ('columnas', models.PositiveIntegerField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='ubicaciones/')),
            ],
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='precio',
            new_name='precio_ticket',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='stock',
        ),
        migrations.AlterField(
            model_name='evento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='evento',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='eventos.ubicacion'),
        ),
        migrations.CreateModel(
            name='AsientoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fila', models.PositiveIntegerField()),
                ('columna', models.PositiveIntegerField()),
                ('disponible', models.BooleanField(default=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asientos', to='eventos.evento')),
            ],
            options={
                'unique_together': {('evento', 'fila', 'columna')},
            },
        ),
    ]
