# Generated by Django 5.2.8 on 2025-11-29 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0012_alter_evento_descripcion_alter_evento_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicacion',
            name='direccion',
            field=models.CharField(max_length=50),
        ),
    ]
