# Generated by Django 5.2.8 on 2025-11-28 20:25

import usuarios.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rut',
            field=models.CharField(max_length=12, unique=True, validators=[usuarios.validators.validar_rut]),
        ),
    ]
