# Generated by Django 5.2.7 on 2025-11-12 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compradetalle',
            name='nombre_asiento',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
