# Generated by Django 5.2.7 on 2025-11-12 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0002_compradetalle_nombre_asiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='compra',
        ),
        migrations.AddField(
            model_name='compra',
            name='asientos_nombres',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='evento_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='pago',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compra.pago'),
        ),
    ]
