# Generated by Django 5.2.7 on 2025-11-12 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0003_remove_pago_compra_compra_asientos_nombres_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='pago',
        ),
        migrations.AddField(
            model_name='pago',
            name='compra',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compra.compra'),
        ),
    ]
