# Generated by Django 5.2.7 on 2025-11-13 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0004_remove_compra_pago_pago_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='total',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
