# Generated by Django 5.2.8 on 2025-11-29 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0006_alter_compra_evento_id_alter_compra_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='estado',
            field=models.CharField(choices=[('completada', 'Completada'), ('cancelada', 'Cancelada')], default='completada', max_length=20),
        ),
    ]
